const ENCODING = 'base64';

const MAIN_NET_LABEL = 'Main Net';
const TEST_NET_LABEL = 'Test Net';

const WALLET_FAVORITE_FLAG = 'favorite';
const WALLET_ARCHIVE_FLAG = 'archive';

const DEFAULT_ADDRESS_PREFIX = 'default_';

enum WALLET_FLAG_ENUM {
  FAVORITE = WALLET_FAVORITE_FLAG,
  ARCHIVE = WALLET_ARCHIVE_FLAG,
}

export {
  ENCODING,
  MAIN_NET_LABEL,
  TEST_NET_LABEL,
  WALLET_FAVORITE_FLAG,
  WALLET_ARCHIVE_FLAG,
  DEFAULT_ADDRESS_PREFIX,
  WALLET_FLAG_ENUM,
};
