export const SET_WALLETS = "SET_WALLETS";
export const INVALIDATE_WALLETS = "INVALIDATE_WALLETS";
export const SET_ADDRESS = "SET_ADDRESS";
export const INVALIDATE_ADDRESS = "INVALIDATE_ADDRESS";




export const SET_TRANSACTIONS = "SET_TRANSACTIONS";
export const SET_BOXES = "SET_BOXES";
export const SET_ASSETS = "SET_ASSETS";
export const SELECT_WALLET = "SELECT_WALLET"
