export const SET_WALLETS = "SET_WALLETS";
export const INVALIDATE_WALLETS = "INVALIDATE_WALLETS";
export const SET_ADDRESS = "SET_ADDRESS";
export const INVALIDATE_ADDRESS = "INVALIDATE_ADDRESS";
export const SET_SUCCESS_SCAN_RESULT = "SET_SUCCESS_SCAN_RESULT";

export const QRCODE_ADD = "QRCODE_ADD"
export const QRCODE_REMOVE = "QRCODE_REMOVE"
